---
# tasks file for ansible-nfs-server
- ansible.builtin.include_tasks: set-facts.yml

- ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- ansible.builtin.include_tasks: config.yml
